version: 2

jobs:
  tests:
    docker:
      - image: circleci/node:12-browsers
    steps:
      - checkout
      - run: npm ci
      - run: npm run lint
      - run: npm test
      - run:
          name: Run integration tests
          command: ./scripts/bin/run-integration-test-circleci.sh
      - store_artifacts:
          path: coverage

workflows:
  version: 2
  test:
    jobs:
      - tests
