version: 2

jobs:
  tests:
    docker:
      - image: cimg/node:16.0-browsers
    steps:
      - checkout
      - run: npm ci
      - run: npm run lint
      - run: npm run build
      - run: npm run test
      - store_artifacts:
          path: coverage

workflows:
  version: 2
  test:
    jobs:
      - tests
